### ISSUE TITLE
Applicatie instellingen beheren

### ISSUE THREAD

**Issue by cmitz** [csvalpha/sofia#176]
Van de volgende zaken zou het beter zijn ze te kunnen managen via de applicatie (front-end)
- [ ] e-mailadres flux (`replyTo` saldomails)
- [ ] saldomail moment & frequentie (`cron`)
- [ ] Rekeningnummer flux
- [ ] OAuth provider settings
