### ISSUE TITLE
Activiteit aanmaken

### ISSUE THREAD

**Issue by cmitz** [csvalpha/sofia#36]
### TODO
- [x] Autocomplete prijslijst
- [ ] Handige datum+tijd picker
- [x] Verplaatsen form naar modal
- [x] Prijslijst selectie wat handiger (#45)
