### ISSUE TITLE
Prijslijst overzicht fixen en testen

### ISSUE THREAD

**Issue by cmitz** [csvalpha/sofia#41]
### TODO
- [x] Waardes goed cachen en terugzetten bij annuleren
- [x] Prijzen kunnen verwijderen
- [x] Bij opslaan waardes direct laten zien (vue?)
- [x] Authorisatie https://sentry.io/share/issue/b3887d21e2154d60b3fc17220d4d15b0/
