### ISSUE TITLE
Saldomutaties (zoals inleg) kunnen aanmaken

### ISSUE THREAD

**Issue by cmitz** [csvalpha/sofia#6]
Even oppervlakkig bedacht: 
- [x] Een knop in User.show waarmee je een modal opent
- [x] In het modal de velden 'Hoeveelheid' en 'Beschrijving'/'Opmerking'
- [x] Na het opslaan een flash message met "Gelukt" oid
- [x] Inleggen tijdens een activiteit (orderscreen)
